graph TD
    N0[__init__.py]
    N1[config_analyzer.py]
    N2[main.py]
    N3[bootstrap.js]
    N4[imageMapResizer.min.js]
    N5[jquery-2.1.0.min.js]
    N6[jquery.bonsai.js]
    N7[less-1.7.0.min.js]
    N8[1_generate_skill.py]
    N9[2_upload_to_chroma.py]
    N10[3_query_example.py]
    N11[generate_clinerules.py]
    N12[context_server.py]
    N13[quickstart.py]
    N14[App.tsx]
    N15[index.tsx]
    N16[generate_cursorrules.py]
    N17[1_generate_skill.py]
    N18[2_build_faiss_index.py]
    N19[3_query_example.py]
    N20[quickstart.py]
    N21[quickstart.py]
    N22[quickstart.py]
    N23[quickstart.py]
    N24[1_generate_skill.py]
    N25[2_upload_to_qdrant.py]
    N26[3_query_example.py]
    N27[test_http_server.py]
    N28[1_generate_skill.py]
    N29[2_upload_to_weaviate.py]
    N30[3_query_example.py]
    N31[generate_windsurfrules.py]
    N32[translate_doc.py]
    N33[__init__.py]
    N34[_version.py]
    N35[__init__.py]
    N36[framework.py]
    N37[models.py]
    N38[runner.py]
    N39[__init__.py]
    N40[__init__.py]
    N41[base.py]
    N42[chroma.py]
    N43[claude.py]
    N44[deepseek.py]
    N45[faiss_helpers.py]
    N46[fireworks.py]
    N47[gemini.py]
    N48[haystack.py]
    N49[kimi.py]
    N50[langchain.py]
    N51[llama_index.py]
    N52[markdown.py]
    N53[minimax.py]
    N54[openai.py]
    N55[openai_compatible.py]
    N56[opencode.py]
    N57[openrouter.py]
    N58[pinecone_adaptor.py]
    N59[qdrant.py]
    N60[qwen.py]
    N61[streaming_adaptor.py]
    N62[together.py]
    N63[weaviate.py]
    N64[ai_enhancer.py]
    N65[api_reference_builder.py]
    N66[architectural_pattern_detector.py]
    N67[__init__.py]
    N68[analyze.py]
    N69[asciidoc.py]
    N70[chat.py]
    N71[common.py]
    N72[confluence.py]
    N73[create.py]
    N74[enhance.py]
    N75[epub.py]
    N76[github.py]
    N77[html.py]
    N78[jupyter.py]
    N79[manpage.py]
    N80[notion.py]
    N81[openapi.py]
    N82[package.py]
    N83[pdf.py]
    N84[pptx.py]
    N85[rss.py]
    N86[scrape.py]
    N87[sync_config.py]
    N88[unified.py]
    N89[upload.py]
    N90[video.py]
    N91[word.py]
    N92[workflow.py]
    N93[asciidoc_scraper.py]
    N94[benchmark_cli.py]
    N95[browser_renderer.py]
    N96[chat_scraper.py]
    N97[cloud_storage_cli.py]
    N98[code_analyzer.py]
    N99[codebase_scraper.py]
    N100[config_command.py]
    N101[config_enhancer.py]
    N102[config_extractor.py]
    N103[config_fetcher.py]
    N104[config_manager.py]
    N105[config_validator.py]
    N106[conflict_detector.py]
    N107[confluence_scraper.py]
    N108[constants.py]
    N109[create_command.py]
    N110[dependency_analyzer.py]
    N111[doc_scraper.py]
    N112[doctor.py]
    N113[embedding_pipeline.py]
    N114[enhance_command.py]
    N115[enhance_skill.py]
    N116[enhance_skill_local.py]
    N117[enhance_status.py]
    N118[enhancement_workflow.py]
    N119[epub_scraper.py]
    N120[estimate_pages.py]
    N121[generate_router.py]
    N122[github_fetcher.py]
    N123[github_scraper.py]
    N124[guide_enhancer.py]
    N125[how_to_guide_builder.py]
    N126[html_scraper.py]
    N127[incremental_updater.py]
    N128[install_agent.py]
    N129[install_skill.py]
    N130[jupyter_scraper.py]
    N131[language_detector.py]
    N132[llms_txt_detector.py]
    N133[llms_txt_downloader.py]
    N134[llms_txt_parser.py]
    N135[main.py]
    N136[man_scraper.py]
    N137[markdown_cleaner.py]
    N138[merge_sources.py]
    N139[multilang_support.py]
    N140[notion_scraper.py]
    N141[openapi_scraper.py]
    N142[opencode_skill_splitter.py]
    N143[package_multi.py]
    N144[package_skill.py]
    N145[__init__.py]
    N146[analyze_parser.py]
    N147[asciidoc_parser.py]
    N148[base.py]
    N149[chat_parser.py]
    N150[config_parser.py]
    N151[confluence_parser.py]
    N152[create_parser.py]
    N153[doctor_parser.py]
    N154[enhance_parser.py]
    N155[enhance_status_parser.py]
    N156[epub_parser.py]
    N157[estimate_parser.py]
    N158[__init__.py]
    N159[base_parser.py]
    N160[formatters.py]
    N161[markdown_parser.py]
    N162[pdf_parser.py]
    N163[quality_scorer.py]
    N164[rst_parser.py]
    N165[unified_structure.py]
    N166[github_parser.py]
    N167[html_parser.py]
    N168[install_agent_parser.py]
    N169[install_parser.py]
    N170[jupyter_parser.py]
    N171[manpage_parser.py]
    N172[multilang_parser.py]
    N173[notion_parser.py]
    N174[openapi_parser.py]
    N175[package_parser.py]
    N176[pdf_parser.py]
    N177[pptx_parser.py]
    N178[quality_parser.py]
    N179[resume_parser.py]
    N180[rss_parser.py]
    N181[scrape_parser.py]
    N182[stream_parser.py]
    N183[sync_config_parser.py]
    N184[test_examples_parser.py]
    N185[unified_parser.py]
    N186[update_parser.py]
    N187[upload_parser.py]
    N188[video_parser.py]
    N189[word_parser.py]
    N190[workflows_parser.py]
    N191[pattern_recognizer.py]
    N192[pdf_extractor_poc.py]
    N193[pdf_scraper.py]
    N194[pptx_scraper.py]
    N195[__init__.py]
    N196[analyze_presets.py]
    N197[github_presets.py]
    N198[manager.py]
    N199[scrape_presets.py]
    N200[quality_checker.py]
    N201[quality_metrics.py]
    N202[rag_chunker.py]
    N203[rate_limit_handler.py]
    N204[resume_command.py]
    N205[rss_scraper.py]
    N206[run_tests.py]
    N207[setup_wizard.py]
    N208[signal_flow_analyzer.py]
    N209[source_detector.py]
    N210[split_config.py]
    N211[__init__.py]
    N212[azure_storage.py]
    N213[base_storage.py]
    N214[gcs_storage.py]
    N215[s3_storage.py]
    N216[streaming_ingest.py]
    N217[swift_patterns.py]
    N218[sync_cli.py]
    N219[sync_config.py]
    N220[test_example_extractor.py]
    N221[test_unified_simple.py]
    N222[unified_codebase_analyzer.py]
    N223[unified_enhancer.py]
    N224[unified_scraper.py]
    N225[unified_skill_builder.py]
    N226[upload_skill.py]
    N227[utils.py]
    N228[video_metadata.py]
    N229[video_models.py]
    N230[video_scraper.py]
    N231[video_segmenter.py]
    N232[video_setup.py]
    N233[video_transcript.py]
    N234[video_visual.py]
    N235[word_scraper.py]
    N236[workflow_runner.py]
    N237[workflows_command.py]
    N238[__init__.py]
    N239[cache.py]
    N240[generator.py]
    N241[models.py]
    N242[server.py]
    N243[__init__.py]
    N244[agent_detector.py]
    N245[git_repo.py]
    N246[server.py]
    N247[server_fastmcp.py]
    N248[server_legacy.py]
    N249[source_manager.py]
    N250[__init__.py]
    N251[config_tools.py]
    N252[packaging_tools.py]
    N253[scraping_tools.py]
    N254[source_tools.py]
    N255[splitting_tools.py]
    N256[sync_config_tools.py]
    N257[vector_db_tools.py]
    N258[workflow_tools.py]
    N259[__init__.py]
    N260[detector.py]
    N261[models.py]
    N262[monitor.py]
    N263[notifier.py]
    N264[__init__.py]
    N265[__init__.py]
    N266[conftest.py]
    N267[test_adaptor_benchmarks.py]
    N268[__init__.py]
    N269[test_adaptors_e2e.py]
    N270[test_base.py]
    N271[test_chroma_adaptor.py]
    N272[test_claude_adaptor.py]
    N273[test_deepseek_adaptor.py]
    N274[test_faiss_adaptor.py]
    N275[test_fireworks_adaptor.py]
    N276[test_gemini_adaptor.py]
    N277[test_haystack_adaptor.py]
    N278[test_kimi_adaptor.py]
    N279[test_langchain_adaptor.py]
    N280[test_llama_index_adaptor.py]
    N281[test_markdown_adaptor.py]
    N282[test_minimax_adaptor.py]
    N283[test_openai_adaptor.py]
    N284[test_openai_compatible_base.py]
    N285[test_opencode_adaptor.py]
    N286[test_openrouter_adaptor.py]
    N287[test_qdrant_adaptor.py]
    N288[test_qwen_adaptor.py]
    N289[test_together_adaptor.py]
    N290[test_weaviate_adaptor.py]
    N291[test_analyze_command.py]
    N292[test_analyze_e2e.py]
    N293[test_api_reference_builder.py]
    N294[test_architecture_scenarios.py]
    N295[test_async_scraping.py]
    N296[test_benchmark.py]
    N297[test_bootstrap_skill.py]
    N298[test_bootstrap_skill_e2e.py]
    N299[test_browser_renderer.py]
    N300[test_c3_integration.py]
    N301[test_chunking_integration.py]
    N302[test_cli_parsers.py]
    N303[test_cli_paths.py]
    N304[test_cli_refactor_e2e.py]
    N305[test_cloud_storage.py]
    N306[test_code_analyzer.py]
    N307[test_codebase_scraper.py]
    N308[test_config_extractor.py]
    N309[test_config_fetcher.py]
    N310[test_config_validation.py]
    N311[test_constants.py]
    N312[test_create_arguments.py]
    N313[test_create_integration_basic.py]
    N314[test_dependency_analyzer.py]
    N315[test_doctor.py]
    N316[test_e2e_three_stream_pipeline.py]
    N317[test_embedding.py]
    N318[test_embedding_pipeline.py]
    N319[test_enhance_command.py]
    N320[test_enhance_skill_local.py]
    N321[test_epub_scraper.py]
    N322[test_estimate_pages.py]
    N323[test_excluded_dirs_config.py]
    N324[test_framework_detection.py]
    N325[test_generate_router_github.py]
    N326[test_git_repo.py]
    N327[test_git_sources_e2e.py]
    N328[test_github_fetcher.py]
    N329[test_github_scraper.py]
    N330[test_guide_enhancer.py]
    N331[test_how_to_guide_builder.py]
    N332[test_incremental_updates.py]
    N333[test_install_agent.py]
    N334[test_install_multiplatform.py]
    N335[test_install_skill.py]
    N336[test_install_skill_e2e.py]
    N337[test_integration.py]
    N338[test_integration_adaptors.py]
    N339[test_issue_219_e2e.py]
    N340[test_issue_277_discord_e2e.py]
    N341[test_issue_277_real_world.py]
    N342[test_kotlin_support.py]
    N343[test_language_detector.py]
    N344[test_llms_txt_detector.py]
    N345[test_llms_txt_downloader.py]
    N346[test_llms_txt_parser.py]
    N347[test_markdown_parsing.py]
    N348[test_mcp_fastmcp.py]
    N349[test_mcp_git_sources.py]
    N350[test_mcp_server.py]
    N351[test_mcp_vector_dbs.py]
    N352[test_mcp_workflow_tools.py]
    N353[test_merge_sources_github.py]
    N354[test_multi_source.py]
    N355[test_multilang_support.py]
    N356[test_new_source_types.py]
    N357[test_opencode_skill_splitter.py]
    N358[test_package_skill.py]
    N359[test_package_structure.py]
    N360[test_parallel_scraping.py]
    N361[test_parser_sync.py]
    N362[test_pattern_recognizer.py]
    N363[test_pdf_advanced_features.py]
    N364[test_pdf_extractor.py]
    N365[test_pdf_scraper.py]
    N366[test_pinecone_adaptor.py]
    N367[test_pr144_concerns.py]
    N368[test_preset_system.py]
    N369[test_quality_checker.py]
    N370[test_quality_metrics.py]
    N371[test_rag_chunker.py]
    N372[test_rate_limit_handler.py]
    N373[test_real_world_fastmcp.py]
    N374[test_scrape_count.py]
    N375[test_scraper_features.py]
    N376[test_server_fastmcp_http.py]
    N377[test_setup_scripts.py]
    N378[test_skip_llms_txt.py]
    N379[test_smart_summarization.py]
    N380[test_source_detector.py]
    N381[test_source_manager.py]
    N382[test_streaming_ingestion.py]
    N383[test_swift_detection.py]
    N384[test_sync_config.py]
    N385[test_sync_config_e2e.py]
    N386[test_terminal_detection.py]
    N387[test_test_example_extractor.py]
    N388[test_unified.py]
    N389[test_unified_analyzer.py]
    N390[test_unified_mcp_integration.py]
    N391[test_unified_parsers.py]
    N392[test_unified_scraper_orchestration.py]
    N393[test_upload_integration.py]
    N394[test_upload_skill.py]
    N395[test_url_conversion.py]
    N396[test_utilities.py]
    N397[test_video_scraper.py]
    N398[test_video_setup.py]
    N399[test_word_scraper.py]
    N400[test_workflow_prompt_injection.py]
    N401[test_workflow_runner.py]
    N402[test_workflow_tools_mcp.py]
    N403[test_workflows_command.py]